theme: minima
title: Site com Jekyll
author: Acaico  
email: acaico@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Esse é o primeiro site que faço com Jekyll. Dizem que ele é mais lento que HUGO, e acredito que seja
  mas, a comunidade dele me parece mais valiosa que sua velocidade.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
